---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDn6KXfObqNILessURcXLf3G1+vrlKy9RPyX2wKGyJyz7diVpCe1nFdWoZgkBmpTbc+wGXMf6u3AexJ0JPfdiT2NIrW5PyenJ6VMoxmxhMApJnSkb6s6bsfm7cn/PzOwX8oGwaxBRTQve9O9Tp3DylI9YXUub0DrTsi5l0wzlM72i1XeOFs9yY2b6PKRu0QOw+CfppZtRyWxEA5KA0Q6jRmpRj6UUgRRuWTjvhC5pPvMsMetQjznkPvGxIFIWKvmNPgkQ/JUh97GMn03X9zYVA5wsjTDpfKFqdXZfCB5rAGyi291LO1/TGMFaHJhz18IQFdDJ2IOCdXsOfdKcgTz9bxHAd6NNr6miTF0ndHFHlS/V3KS5Je+ao+skwQi3YGUGQTSjqROqoHcvE0scs76Wo/AT5IkVjjz7gYJltHpTu31bsDngppmWqXdLmd05tcHgsD8RZbQM9P3pYqkUiWnCHjiE2Or6UC+zvAAkaHx059j0b6IyLSBeWfkcpD8NEwL7QpZ+7Z68zP9uGhmsVtBkP5aoAhLyg/AZr0oGdAPe7V+gr2wbeHqa9QHS5yYVanr3Z1PKakVhehpXSo0k3xWPif3wj2XkAvoBv2W6+QCbKfQE9fuuAVTzDn/5gKe0TjjhjsYMi8N/87H+5ek/px1sTzLvqtCvJCLgSBzEeFP0Z5qKUyad+lW1/6qb4RQwigq7rGLNLsn7leACc=
    admin-user: AgASs/j068C9JYrsWklKQE/CKJ55+3FXMeNYJwcNf4RwkRlkZs9S02HnmDkNYnDQovNAL4OqPx9BsTVY0awjHrCuvMFtShInwIjjvLs5ha6WGIdjkiZ7BanaSXhaFRH/t9e1q8AeDw0KSXq1/wTccLnH9XY7EJ2R/dIvH9SUQNx7xtnetLemfK+oXwpKKRAor6u5ROkYLKToyjQ3XDjC++Oib7db0xOBk568gBBYOUaIdIr0VNwDrDZgSUvH9+5/dB9xYQViMEHvSJVe3ysYLsiIoTvw0rqk5yFe0WIwupZ4yGcdLF/BbEx261OjDhBnquSyIsz5potPDUjBuiOInyLAUXZdRnBlLyO1WCdq7EcqDkijRM2lDYa1SjjTVk1ZsrktH1o3IfVdqeFvDlj+7x/KGLzdiqDFmGS0knQaEtR6855DNjuZEFX90YynEpx5pQFoyJ67f1CkZ2qcQyI1WSEL3diz7NS13ASkGkFzxloN5UiHStAa/lXLhGnqhcCl23yD2akCCCBvj0LTYcCviWNV/SPXhYrnJRaXT5Yde+T+Zh/SUel2MQjzL6zQE3fqV/OGtxAfslJydCxdQqfxVQdauv17jRBxNIuhyTICeSzgo868nhPMK87OcBv6Az4mKQObCBXpnAHOXOx7hnqUVU/dPbiklyPnhpnOg7+dD3an1hFqsRZ0VjNQC9dChImKdM5o/K5oRw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
