---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-client
  namespace: doongle
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgBmWI7Fn8xon85N6qga0MrqrtqhazZ6mPiGaug5BSi9a6IcAmfVzvFQyJLBp5qkdFJrqRUdOTebNz4Vl6SHqZhX+1Fa9bze62sO9SNQFHkxnZIFeK6qubfRqitdsclSGkY/3nvPA7BL2LimCIUevKnW/myi+qr6sVVC85DwrCY7FHNPorh2R8j9yckqgmL+3N8kiS+SUMyp4o+tfD37e1f28BZ/xXOVktkDcRY1HiMnsjxsIZ/uRNgfGg8+lh5YAXuNPC4B7EiAEKLUm3sZUYKH4P93M90GvB20Y2/IuAMUOXsjpvPVjxcEpr3lPw1xMefT3+fMTjnhsZoTPYLdiWgczYGaONaJ5e2j/kSu0NV+ROcyJXJ6ZcfRK9+AN3NrEbcES3aJTMDTHyotQ1Z0dXQYpqPwODbpU8plYCGaXIWqfPdFTYDTlQZ11h9ob5hn4IS6LgfVHn+t7S/iWVMXi/X9JelMoWaYTGxqMG2k1BUHZcnjXluM9gOp9koYpKoXRhsRtL4VPiKapPOSCgNT12ff3O5zINfjXTXIJalpnvI9pfYX5xM8/CxAI5ozM8cW6UQrivxaGGEO+XQsgXHiQSEVH89IHfDbQ4mUSwAT+5vBbTxTvalDhPROjGwrJULlu4C0zRFWDnt+LWth1hiEVUjagL4MUm3JMGJs15EHTJtRu6clv/sFsMrX/6nrCBUJyr3rWvh3Z25ztRv7
    MINIO_SECRET_KEY: AgDe2nmYPVvP/IezBjbuNpzKm9Xt6U4L0V5PAK2ajNGPmOK/GLWMd/AW/h6kd9zP9IPuZeEVuYbfWl26gVg6L1kGmG4sswOYExQF+9ofovJkKlGispST2+a85vNuRqRPZi0HL3lw8RQgZgYDgvzqjuBVzaGeEQ7x7ks8xqGy/qCa+S/vJDfCIf5AykY7k7wFykFBnR9YKdkNquQGzLzeGF/i5C7wBDgpwjiS9O3TzlV3pf4lZuYkjvoEXF4XpsQHndfhcBalkIuqaT7RYpt5Dly2i2f3bAE61y+lhWfHStXMgy6ny+F2mOcdEf06tPbHG4/nx6dgV1XBKfuyUXpoGLGl9KC98FFzReaZoT53CgWML1cCRPOvgIKYKEl7u/gMok45MQK2dAkvg7svpCn+eDgy5+RjJVhtFTLJpvAjhC0xLD6lQ2AVeQdmOC6PkV1AXpPsxYjjgvUPNbdZTOr/I6qCSAjSXSO0aCUfhsWeKxVhRxxg7hO8Bgpu9K3+e1e9eOMPi0HZ2UNPdY8Qa9+oxfa7yth2hQdK9xoAey7iMU4kCQuJkmwH1duOXlT9+yhZTLhQl5nh6QfJ0y+hC20i78D2WPtxDOpbib7SxQzVdOPtB4H3r1lmNfD4xAp0ak1wRZwAL6p9Ko+aPgnrQrMubFd1osgi7ZFcTmcK01CmqIg8aoewVq6yCo7OB6dB6Yq6kglLqFghM1WJWg==
  template:
    metadata:
      name: minio-client
      namespace: doongle
