---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: doongle
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCTot8vwfGZ3LQA+f/YHvgFpnYXfX27zpDoOhYBQ2jGhwB/Zn4s/INhiXatodwTbWelsdf3nU1qdInc4f4dM1Mw+Rq9k+/xnSBNaD6bi8uHt3l/uDVgTN+SrFPVogno3GzZEEer0JQHLEFB9VRKaRkLDedlBfIFPkl5wzNFeB/c9L29/7qJw9Z3kM8ZYD5lfGUiXRIZI+zcmIHioUfkqimpFQVFuTYKMeQtupVGB7UjA2kMNpDBh5xGC2LWZafTrdzKj4LTHQOtSSxz4UPE14uL8u8QcD4D6h0/Mtk1Jft+iDSV/ZaqGfj2xr6O1wVu9HjH7/Jxat/loHLlPhFBZ0y2FpYPxfUP6+GJHdPl1ackwKnhERavGIzJtuO+a+Nqn9zSbZE4heeyZYZSxjBiAowJYVvO+qvHNA5Lw+WSe8VcURzKP/qEQILrfW8joAib8wAggBYCxgjWv9AhFs33YcdfSZdScI3aKrli2KX4Qd4B0rzjYj+vooG8mGBjyq3Zmx45dVBX4gY031+163ywMKnlWFUYEvIs5gfaNl/GeaESMKzt9UFy53ZmgI8zBn4K2xhH1TgaeSbpsnadWxzCWNIcFqf+SqA5DpG/YAmBRJs7H8HKK/9556V2hG5nmRA0NqSJPi5OfhOOxZ+nu1TI4YXlJUI0onFB47RbjXqnSo12+cyJH0+NiQ250f5fIwsVB3tzRLvRqU5Mlg==
    MINIO_ROOT_USER: AgBWQtvBPMrs1ATQ7A0ad7kqkwNDASB3Clrqzoprd06dXeeNZplRt8kpne59WTWqcql2S3MFFq8wA7HbVUNO1zz8I7cQT60LKjHC++Qdvb81TFikKtWVigvSLCKukxEmrFstsLRCe7UwCViVIVi5WCTkCBmXOdQFOskBdGaXtgn5AGhp9S9l4maxM56k3AZwCmEncKNJ78dcISIcmRKqNydgxnVbwccTMoPEmiM+YiRUpSs1vLV0REUwzpg2xiO7qyfLrwiYa/quEY0rwxIlWZVC/gHFGsajtvPuqcSuQD/ycdqtHSCKv3UgtGvyero18xdFut2fVMgMF8NYBLeJWlCEIz8gZHvEIugF4CAkpg+J0PFJ+buB7yFRZK2U1MgKQhtEoZT+D/cIufOkIGO2+QROheCdAXifozLKFXvOjw3hOTCl5PpOfnE67UQMoDpV1iJ7Q4dv/QLwY2+yjl7djzZtAOup+aa0NlhGOVHex8tqYMpDxdNRr89yidwus+3VKh/P23LesUCIwFb/FBiYGWuhdcWAS3SwzmClY/tukLliMgScP8C+FJcJB9tr27W67TC0Nkk1wh7HKPznem/7ZFmZJyhoiazpNfOVGBaopoW4rwl+KZ9OZ7o7LAmEFgzvN4ZJQVv/RckdgzHNmJUCucr9W2SbIr6at+0mS3SoI/mjp1SYToJ4JNcysF7dzacgKKCxQjMv08NsK6rk
  template:
    metadata:
      name: minio-credentials
      namespace: doongle
    type: Opaque
