# minio/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: doongle
type: Opaque
stringData:                          # base64 인코딩 안 하고 평문으로 작성 (k8s가 자동 인코딩)
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: test1234
