apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  clusterIP: None          # Headless (StatefulSet용, Pod에 고유 DNS 부여)
  selector:
    app: kafka
  ports:
  - name: broker
    port: 9092
