# api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doongle-api
  namespace: doongle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doongle-api
  template:
    metadata:
      labels:
        app: doongle-api
    spec:
      nodeSelector:
        kubernetes.io/hostname: desktop-6iceuch   # 윈2 일반노드 (api는 GPU 불필요)
      containers:
      - name: api
        image: ghcr.io/lucid9512/doongle-api:latest
        imagePullPolicy: Always                     # latest 태그라 항상 최신
        envFrom:                                    # ConfigMap + Secret 통째 주입
        - configMapRef:
            name: doongle-config
        - secretRef:
            name: postgres-credentials
        - secretRef:
            name: minio-client
        - secretRef:                    # ← 이거 추가
            name: doongle-app-secret    # SECRET_KEY / ADMIN_SECRET_KEY / JWT_SECRETCRET_KEY
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"                         # 윈2 RAM 빠듯 → Kafka와 공존하게 작게
